### ISSUE TITLE
Installing package

### ISSUE THREAD

**Issue by estebanbeck** [orijitghosh/VANESSA-DAM#1]
Hi, 

I am getting an error with the installation from remote. 

I run
```
if (!require("remotes")) install.packages("remotes")
remotes::install_github("orijitghosh/VANESSA-DAM", subdir = "VANESSA-DAM-CRA/vanessadamcra")
remotes::install_github("orijitghosh/VANESSA-DAM", subdir = "VANESSA-DAM-SA/vanessadamsa")
```

and I get
```
> if (!require("remotes")) install.packages("remotes")
Loading required package: remotes
> remotes::install_github("orijitghosh/VANESSA-DAM", subdir = "VANESSA-DAM-CRA/vanessadamcra")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`orijitghosh`) and repo name (`VANESSA-DAM`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

In addition. I work with ethoscope data (not DAM), do you have an easy way to run it in your package? Thanks!

**Comment by orijitghosh** [comment]
Hi @estebanbeck ,

I could not replicate this installation issue; however, I suspect you must update the `remotes` package. Can you please do that and let me know if that works? I have tested in multiple machines running different OSs; with a recent installation of `remotes`, these commands install the packages without any problems. See this for more info: https://github.com/r-lib/remotes/pull/510

About your ethoscope data, currently the versions of VANESSA do not accept ethoscope data. But I can make a version for ethoscopes, it should not require many changes, just the initial data processing will be different. I will try to work on it and update here once I am done.
