### ISSUE TITLE
shinny app

### ISSUE THREAD

**Issue by yangskyfucker** [orijitghosh/VANESSA-DAM#2]
when I use demo data, I have encountered this problem, how to operate

![image](https://user-images.githubusercontent.com/69762935/192615240-8bce89c7-8438-4426-b3fb-89c3eae2fe6c.png)

**Comment by orijitghosh** [comment]
@yangskyfucker , Seeing you already closed this issue, I hope it worked for you!

**Comment by yangskyfucker** [comment]
Once the data is loaded, all the colors at right box also need to set, and then it works. It's a great package. Thank you! @orijitghosh

**Comment by orijitghosh** [comment]
Glad you liked it. Let me know if you have any suggestions/feedback. One tip for successful usage is to fix all parameters (including colors, etc.) before uploading monitor and metadata files.
