### ISSUE TITLE
Shiny Run Error

### ISSUE THREAD

**Issue by mantouyangmeng** [orijitghosh/VANESSA-DAM#5]
Hello, when I run the following code I get a different error and the data used is also the demo data provided

Question 1
> library(vanessadamsa)
> runVanessaDamSa()
Listening on http://127.0.0.1:6210
Warning: Good news!
You don't need to call `useShinyalert()` anymore. Please remove this line from your code.
If you really want to pre-load {shinyalert} to the UI for any reason, use:
	`useShinyalert(force = TRUE)`
Warning: Error in observe: object 'bout_summary' not found
  2: shiny::runApp
  1: runVanessaDamSa

Question 2
> library(vanessadamcra)
> runVanessaDamCra()
Warning: The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.
Warning: Error in observe: object 'dt_curated' not found
  2: shiny::runApp
  1: runVanessaDamCra

Shiny enters the data at the end and then flashes back; I am not sure why, but I am hoping I can get an answer. Thank you very much!

**Comment by orijitghosh** [comment]
@mantouyangmeng , sorry for the delayed response. From the warnings you posted, it does not seem like there is an `error`. There are a few `warnings` which should not affect the functionalities of the app. Please let me know if you get any error message, and the app crashes.
